### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/tapable#12]
If we wanted to tackle migrating all of webpack to typescript, we would need to start with all of the supporting libs. Especially this one. Stubbing this for implementation down the road.

**Comment by zhaoshengjun** [comment]
Do you need any help? I am interested in writing typescript. :smiley:

**Comment by TheLarkInn** [comment]
By all means I'll close this PR and you can take a crack at it.

**Comment by zhaoshengjun** [comment]
Sorry @TheLarkInn , I didn't see your PR. I thought it's just the discussion phase. 

No need to close your PR.

**Comment by TheLarkInn** [comment]
No it's not a problem at all. Infact there were a few things I was struggling with (that are TS limitations for some of our functions which take a callback as the last argument). If you would like to take some time to investigate converting this over I would love to see this. Also you can use the existing tests to ensure your TS changes are valid when compiled.

**Comment by zhaoshengjun** [comment]
Hi @TheLarkInn ,

I've been struggling with this in the past few days. Because converting it to typescript without breaking it is rather simple. But make it more extendable is a totally different work. Also I think the callback style is not great for reading/maintaining perspective. Then I realised that the problem is I don't know the expectations. 

So what's the purpose of this initiative? Is it simply converting to typescript, adding type annotation? Or we can use this to make it better? e.g: use promise instead of callback like suggested in #11 ?

I think it needs some directions from the core team to clarify on this. Thanks!

**Comment by TheLarkInn** [comment]
The main goal for now would be to convert it to Typescript and add types. But in a way in which it would prevent the existing tests and APIs from not breaking. 

I agree that this could be more extensible but for now I want to have it in a working state.

**Comment by Kinrany** [comment]
Typescript's types improved a lot in the past two years. Any plans to reopen this issue?

**Comment by evilebottnawi** [comment]
@Kinrany no, we use pure javascript for better maintenance projects, somebody can use `flow`, somebody `typescript`, somebody other, we use `typescript` comments for check types
