### ISSUE TITLE
has `hooks.hookName.taps` been not recommanded?

### ISSUE THREAD

**Issue by gylidian** [webpack/tapable#152]
When I use this property `.taps` with typescript, It will prompt you that the property does not exist

![image](https://user-images.githubusercontent.com/30214981/101437280-c88d5200-394a-11eb-8604-fe15c38eaf4a.png)

In fact, i found this usage in the webpack source code

![image](https://user-images.githubusercontent.com/30214981/101437331-eeb2f200-394a-11eb-9ceb-8d2d096713f8.png)

`tapable.d.ts`:

![image](https://user-images.githubusercontent.com/30214981/101437584-78fb5600-394b-11eb-8ef8-47a0dfb7b708.png)

**Comment by alexander-akait** [comment]
Feel free to fix types

**Comment by gylidian** [comment]
@alexander-akait 

> Feel free to fix types

I just want to make sure whether users are not recommended to use this feature

Okay, i'll make a pr to fix it

**Comment by Shinyaigeek** [comment]
I'm facing the same issue.
any progress on this issue? If you don't mind, I would like to pick this issue.

**Comment by Shinyaigeek** [comment]
I'm wondering whether `hooks.[hookname].taps` property should be public.
`hooks.[hookname].taps` seems to be private value used only in tapable’s inner process. (refering to `hooks.[hookname].taps` does not exist in also tapable's README, not only in type definitions)

In code in screenshots, `hooks.[hookname].taps` is accessed in order to copy A Hook’s taps into B Hook. in my opinion, it is better that tapable provide method to fullfill such a requisition
